# Stenographer configuration

# URL to reach the backend API for transcriptions.
base_url: http://localai.example.org/v1

# The name of the API model.
model_name: tiny

# The default language of voice messages.
# https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
# Set to `auto` for auto-detect.
language: auto

# API key
api_key: mysecretkey

# A reaction to trigger a transcription job.
# This is usually some emoji. Put the empty string '' to disable.
reaction: 🔇

# Whether the bot should respond automatically to voice messages.
# Setting this to `false` only makes sense when triggering with
# a reaction is enabled.
auto: true